User.create!([
  {email: "person1@gmail.com", password: "password", reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2018-04-07 09:15:28", last_sign_in_at: "2018-04-07 08:44:59", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", fname: "Person", lname: "One", dob: "2018-04-07", admin: nil},
  {email: "admin@grocerystore.ie", password: "password", reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2018-04-07 09:27:15", last_sign_in_at: "2018-04-07 08:47:04", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", fname: "Admin", lname: "User", dob: "2018-04-07", admin: true}
])
Category.create!([
  {name: "Biscuits"},
  {name: "Bread"},
  {name: "Cakes & Pies"},
  {name: "Cereals"},
  {name: "Cheese"},
  {name: "Chocolate & Sweets"},
  {name: "Condiments, Sauces & Dips"},
  {name: "Cooking Ingredients"},
  {name: "Crisps, Nuts, & Popcorn"},
  {name: "Dairy Alternatives"},
  {name: "Desserts - Chilled"},
  {name: "Desserts - Frozen"},
  {name: "Doughnuts, Muffins, & Cookies"},
  {name: "Fish - Frozen"},
  {name: "Fish - Fresh"},
  {name: "Frozen Foods"},
  {name: "Hot Chocolates"},
  {name: "Meat - Cooked"},
  {name: "Meat - Fresh"},
  {name: "Meat - Frozen"},
  {name: "Milk, Butter, & Eggs"},
  {name: "Organic"},
  {name: "Pastries"},
  {name: "Poultry - Fresh"},
  {name: "Poultry - Frozen"},
  {name: "Readymade Meals"},
  {name: "Salads & Dips"},
  {name: "Sausages, Burgers, & BBQ"},
  {name: "Soft Drinks"},
  {name: "Sugars & Sweeteners"},
  {name: "Tea & Coffee"},
  {name: "Tins & Packets"},
  {name: "Water"},
  {name: "Vegetables - Fresh"},
  {name: "Vegetables - Frozen"},
  {name: "Vegetables - Yoghurts"}
])
Product.create!([
  {title: "7up", price: "1.49", desc: "Lemon & Lime Flavoured Soft Drink", image_url: "7up.jpg", user_id: 2, category_id: 29},
  {title: "Heinz Beans 4 Pack", price: "4.2", desc: "Heinz tinned beans. Package contains 4x600g tins", image_url: "beans.jpg", user_id: 2, category_id: 32},
  {title: " Brennans Sliced Pan White", price: "1.5", desc: "Family Pan Premium White Bread. 800G", image_url: "brennans.jpg", user_id: 2, category_id: 2},
  {title: "Birds Eye Premium Beef Burgers", price: "4.75", desc: "Birds Eye Premium 4 Beef Quarter Pounder Burgers with seasoning. 454G", image_url: "burgers.jpg", user_id: 2, category_id: 20},
  {title: "Charleville Cheese", price: "2.0", desc: "Charleville Reduced Fat Red Cheddar Cheese. 200 G", image_url: "cheese.jpg", user_id: 2, category_id: 5},
  {title: " Nescafe Gold Blend Coffee", price: "6.5", desc: "Nescafe is instant coffee with a smooth, distinctive flavour and rich aroma. 200G", image_url: "coffee.jpg", user_id: 2, category_id: 31},
  {title: "Ballyfree Free Range Eggs", price: "2.69", desc: "Ballyfree Free Range Eggs Very Large 6 Pack", image_url: "eggs.jpg", user_id: 2, category_id: 21},
  {title: "Evian Natural Mineral Water 6 Pack", price: "5.45", desc: "Naturally pure, from the French alps\r\nPerfect for staying hydrated throughout the day. 6x 1.5L Bottles", image_url: "evian.jpg", user_id: 2, category_id: 33},
  {title: "Cadbury Hot Chocolate", price: "4.99", desc: "Cadbury Fair Trade Hot Chocolate Instant 400G", image_url: "hotchocolate.jpg", user_id: 2, category_id: 17},
  {title: "Heinz Ketchup 570G", price: "2.5", desc: "Heinz Top Down Squeezy Tomato Ketchup Sauce 570G", image_url: "ketchup.jpg", user_id: 2, category_id: 7},
  {title: " Avonmore Milk 2 Litre", price: "1.89", desc: "Pasteurised and Homogenised Whole Milk", image_url: "milk.jpg", user_id: 2, category_id: 21},
  {title: " Mc Donnells Super Noodles Chicken 65G", price: "1.49", desc: "Tender Roast Chicken Flavour Instant Noodles.\r\nBest ever flavour\r\nNo artificial preservatives or colours", image_url: "noodles.jpg", user_id: 2, category_id: 32},
  {title: " Roma Baby Pasta Shells 500G", price: "1.69", desc: "Cooks in 7 mins\r\n100% durum wheat pasta\r\nSource of protein\r\nLow fat", image_url: "pasta.jpg", user_id: 2, category_id: 23},
  {title: "Sweet Potatoes Loose", price: "0.49", desc: "These subtle sweet potatoes are also great for mashing, roasting and wedges.\r\nDistinctively sweet and soft.", image_url: "potato.jpg", user_id: 2, category_id: 34},
  {title: "Nolans Prawns", price: "3.5", desc: "Nolans Prawn Cocktail Regular 170G", image_url: "prawns.jpg", user_id: 2, category_id: 14}
])
